import fs from "fs";

const countries = JSON.parse(fs.readFileSync("src/data/countries.json", "utf-8"));

const capitalData = {
  af: { capital: "Kabul", major: ["Herat", "Kandahar", "Mazar-i-Sharif"] },
  al: { capital: "Tirana", major: ["Durrës", "Vlorë"] },
  dz: { capital: "Algiers", major: ["Oran", "Constantine", "Annaba"] },
  ad: { capital: "Andorra la Vella", major: ["Escaldes-Engordany"] },
  ao: { capital: "Luanda", major: ["Huambo", "Benguela"] },
  ag: { capital: "Saint John's", major: [] },
  ar: { capital: "Buenos Aires", major: ["Córdoba", "Rosario", "Mendoza", "La Plata"] },
  am: { capital: "Yerevan", major: ["Gyumri"] },
  au: { capital: "Canberra", major: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"] },
  at: { capital: "Vienna", major: ["Graz", "Linz", "Salzburg"] },
  az: { capital: "Baku", major: ["Ganja", "Sumqayit"] },
  bs: { capital: "Nassau", major: [] },
  bh: { capital: "Manama", major: ["Riffa"] },
  bd: { capital: "Dhaka", major: ["Chittagong", "Khulna", "Rajshahi"] },
  bb: { capital: "Bridgetown", major: [] },
  by: { capital: "Minsk", major: ["Gomel", "Mogilev", "Vitebsk"] },
  be: { capital: "Brussels", major: ["Antwerp", "Ghent", "Charleroi", "Liège"] },
  bz: { capital: "Belmopan", major: ["Belize City"] },
  bj: { capital: "Porto-Novo", major: ["Cotonou", "Abomey-Calavi"] },
  bt: { capital: "Thimphu", major: ["Phuntsholing"] },
  bo: { capital: "Sucre", major: ["La Paz", "Santa Cruz", "Cochabamba"] },
  ba: { capital: "Sarajevo", major: ["Banja Luka", "Tuzla", "Zenica"] },
  bw: { capital: "Gaborone", major: ["Francistown", "Molepolole"] },
  br: { capital: "Brasília", major: ["São Paulo", "Rio de Janeiro", "Salvador", "Fortaleza", "Belo Horizonte", "Curitiba", "Manaus"] },
  bn: { capital: "Bandar Seri Begawan", major: [] },
  bg: { capital: "Sofia", major: ["Plovdiv", "Varna", "Burgas"] },
  bf: { capital: "Ouagadougou", major: ["Bobo-Dioulasso"] },
  bi: { capital: "Gitega", major: ["Bujumbura"] },
  cv: { capital: "Praia", major: ["Mindelo"] },
  kh: { capital: "Phnom Penh", major: ["Siem Reap", "Battambang"] },
  cm: { capital: "Yaoundé", major: ["Douala", "Garoua"] },
  ca: { capital: "Ottawa", major: ["Toronto", "Vancouver", "Montreal", "Calgary", "Edmonton", "Quebec City", "Winnipeg"] },
  cf: { capital: "Bangui", major: [] },
  td: { capital: "N'Djamena", major: ["Moundou"] },
  cl: { capital: "Santiago", major: ["Valparaíso", "Concepción", "La Serena"] },
  cn: { capital: "Beijing", major: ["Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Nanjing", "Chongqing", "Tianjin"] },
  co: { capital: "Bogotá", major: ["Medellín", "Cali", "Barranquilla", "Cartagena"] },
  km: { capital: "Moroni", major: [] },
  cg: { capital: "Brazzaville", major: ["Pointe-Noire"] },
  cd: { capital: "Kinshasa", major: ["Lubumbashi", "Mbuji-Mayi", "Bukavu", "Kisangani"] },
  cr: { capital: "San José", major: ["Alajuela", "Cartago"] },
  ci: { capital: "Yamoussoukro", major: ["Abidjan", "Bouaké"] },
  hr: { capital: "Zagreb", major: ["Split", "Rijeka", "Osijek"] },
  cu: { capital: "Havana", major: ["Santiago de Cuba", "Camagüey"] },
  cy: { capital: "Nicosia", major: ["Limassol", "Larnaca"] },
  cz: { capital: "Prague", major: ["Brno", "Ostrava", "Plzeň"] },
  dk: { capital: "Copenhagen", major: ["Aarhus", "Odense", "Aalborg"] },
  dj: { capital: "Djibouti City", major: [] },
  dm: { capital: "Roseau", major: [] },
  do: { capital: "Santo Domingo", major: ["Santiago de los Caballeros", "La Romana"] },
  ec: { capital: "Quito", major: ["Guayaquil", "Cuenca", "Santo Domingo"] },
  eg: { capital: "Cairo", major: ["Alexandria", "Giza", "Luxor", "Port Said"] },
  sv: { capital: "San Salvador", major: ["Santa Ana", "San Miguel"] },
  gq: { capital: "Malabo", major: ["Bata"] },
  er: { capital: "Asmara", major: ["Keren"] },
  ee: { capital: "Tallinn", major: ["Tartu", "Narva"] },
  sz: { capital: "Mbabane", major: ["Manzini"] },
  et: { capital: "Addis Ababa", major: ["Dire Dawa", "Bahir Dar", "Gondar"] },
  fj: { capital: "Suva", major: ["Nadi", "Lautoka"] },
  fi: { capital: "Helsinki", major: ["Espoo", "Tampere", "Turku", "Oulu"] },
  fr: { capital: "Paris", major: ["Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"] },
  ga: { capital: "Libreville", major: ["Port-Gentil"] },
  gm: { capital: "Banjul", major: ["Serekunda"] },
  ge: { capital: "Tbilisi", major: ["Batumi", "Kutaisi"] },
  de: { capital: "Berlin", major: ["Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dresden", "Hanover"] },
  gh: { capital: "Accra", major: ["Kumasi", "Sekondi-Takoradi"] },
  gr: { capital: "Athens", major: ["Thessaloniki", "Patras", "Heraklion"] },
  gd: { capital: "Saint George's", major: [] },
  gt: { capital: "Guatemala City", major: ["Quetzaltenango"] },
  gn: { capital: "Conakry", major: ["Nzérékoré"] },
  gw: { capital: "Bissau", major: [] },
  gy: { capital: "Georgetown", major: ["Linden"] },
  ht: { capital: "Port-au-Prince", major: ["Cap-Haïtien"] },
  hn: { capital: "Tegucigalpa", major: ["San Pedro Sula"] },
  hu: { capital: "Budapest", major: ["Debrecen", "Szeged", "Miskolc"] },
  is: { capital: "Reykjavik", major: ["Kópavogur"] },
  in: { capital: "New Delhi", major: ["Mumbai", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow", "Surat"] },
  id: { capital: "Jakarta", major: ["Surabaya", "Bandung", "Medan", "Semarang", "Makassar"] },
  ir: { capital: "Tehran", major: ["Mashhad", "Isfahan", "Shiraz", "Tabriz", "Karaj"] },
  iq: { capital: "Baghdad", major: ["Basra", "Mosul", "Erbil", "Kirkuk"] },
  ie: { capital: "Dublin", major: ["Cork", "Limerick", "Galway"] },
  il: { capital: "Jerusalem", major: ["Tel Aviv", "Haifa", "Rishon LeZion"] },
  it: { capital: "Rome", major: ["Milan", "Naples", "Turin", "Palermo", "Bologna", "Florence", "Catania", "Venice", "Verona"] },
  jm: { capital: "Kingston", major: ["Montego Bay", "Spanish Town"] },
  jp: { capital: "Tokyo", major: ["Osaka", "Yokohama", "Nagoya", "Sapporo", "Fukuoka", "Kyoto", "Kobe", "Kawasaki", "Saitama"] },
  jo: { capital: "Amman", major: ["Zarqa", "Irbid"] },
  kz: { capital: "Astana", major: ["Almaty", "Shymkent", "Karaganda"] },
  ke: { capital: "Nairobi", major: ["Mombasa", "Kisumu", "Nakuru"] },
  ki: { capital: "Tarawa", major: [] },
  kw: { capital: "Kuwait City", major: ["Al Ahmadi"] },
  kg: { capital: "Bishkek", major: ["Osh"] },
  la: { capital: "Vientiane", major: ["Luang Prabang", "Savannakhet"] },
  lv: { capital: "Riga", major: ["Daugavpils", "Liepāja"] },
  lb: { capital: "Beirut", major: ["Tripoli", "Sidon"] },
  ls: { capital: "Maseru", major: [] },
  lr: { capital: "Monrovia", major: [] },
  ly: { capital: "Tripoli", major: ["Benghazi", "Misrata"] },
  li: { capital: "Vaduz", major: ["Schaan"] },
  lt: { capital: "Vilnius", major: ["Kaunas", "Klaipėda", "Šiauliai"] },
  lu: { capital: "Luxembourg City", major: ["Esch-sur-Alzette"] },
  mg: { capital: "Antananarivo", major: ["Toamasina", "Antsirabe"] },
  mw: { capital: "Lilongwe", major: ["Blantyre", "Mzuzu"] },
  my: { capital: "Kuala Lumpur", major: ["George Town", "Johor Bahru", "Ipoh", "Shah Alam"] },
  mv: { capital: "Malé", major: [] },
  ml: { capital: "Bamako", major: ["Sikasso"] },
  mt: { capital: "Valletta", major: ["Birkirkara", "Mosta"] },
  mh: { capital: "Majuro", major: [] },
  mr: { capital: "Nouakchott", major: ["Nouadhibou"] },
  mu: { capital: "Port Louis", major: ["Curepipe"] },
  mx: { capital: "Mexico City", major: ["Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Cancún"] },
  fm: { capital: "Palikir", major: [] },
  md: { capital: "Chișinău", major: ["Bălți", "Tiraspol"] },
  mc: { capital: "Monaco", major: [] },
  mn: { capital: "Ulaanbaatar", major: ["Darkhan", "Erdenet"] },
  me: { capital: "Podgorica", major: ["Nikšić", "Bar"] },
  ma: { capital: "Rabat", major: ["Casablanca", "Marrakech", "Fez", "Tangier", "Agadir"] },
  mz: { capital: "Maputo", major: ["Matola", "Beira", "Nampula"] },
  mm: { capital: "Naypyidaw", major: ["Yangon", "Mandalay"] },
  na: { capital: "Windhoek", major: ["Walvis Bay"] },
  nr: { capital: "Yaren", major: [] },
  np: { capital: "Kathmandu", major: ["Pokhara", "Lalitpur", "Bharatpur"] },
  nl: { capital: "Amsterdam", major: ["Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen"] },
  nz: { capital: "Wellington", major: ["Auckland", "Christchurch", "Hamilton", "Tauranga"] },
  ni: { capital: "Managua", major: ["León", "Granada"] },
  ne: { capital: "Niamey", major: ["Zinder"] },
  ng: { capital: "Abuja", major: ["Lagos", "Kano", "Ibadan", "Port Harcourt", "Benin City"] },
  kp: { capital: "Pyongyang", major: ["Hamhung", "Chongjin"] },
  mk: { capital: "Skopje", major: ["Bitola", "Ohrid"] },
  no: { capital: "Oslo", major: ["Bergen", "Trondheim", "Stavanger", "Drammen"] },
  om: { capital: "Muscat", major: ["Salalah", "Sohar"] },
  pk: { capital: "Islamabad", major: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan"] },
  pw: { capital: "Ngerulmud", major: ["Koror"] },
  ps: { capital: "Ramallah", major: ["Gaza City", "Hebron"] },
  pa: { capital: "Panama City", major: ["Colón", "David"] },
  pg: { capital: "Port Moresby", major: ["Lae"] },
  py: { capital: "Asunción", major: ["Ciudad del Este", "Encarnación"] },
  pe: { capital: "Lima", major: ["Arequipa", "Cusco", "Trujillo", "Chiclayo"] },
  ph: { capital: "Manila", major: ["Quezon City", "Davao City", "Cebu City", "Zamboanga City", "Bacolod"] },
  pl: { capital: "Warsaw", major: ["Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin"] },
  pt: { capital: "Lisbon", major: ["Porto", "Braga", "Coimbra", "Funchal"] },
  qa: { capital: "Doha", major: ["Al Rayyan"] },
  ro: { capital: "Bucharest", major: ["Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Brașov"] },
  ru: { capital: "Moscow", major: ["Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don"] },
  rw: { capital: "Kigali", major: ["Butare"] },
  kn: { capital: "Basseterre", major: [] },
  lc: { capital: "Castries", major: [] },
  vc: { capital: "Kingstown", major: [] },
  ws: { capital: "Apia", major: [] },
  sm: { capital: "San Marino", major: [] },
  st: { capital: "São Tomé", major: [] },
  sa: { capital: "Riyadh", major: ["Jeddah", "Mecca", "Medina", "Dammam", "Khobar"] },
  sn: { capital: "Dakar", major: ["Thiès", "Saint-Louis"] },
  rs: { capital: "Belgrade", major: ["Novi Sad", "Niš", "Kragujevac"] },
  sc: { capital: "Victoria", major: [] },
  sl: { capital: "Freetown", major: ["Bo"] },
  sg: { capital: "Singapore", major: [] },
  sk: { capital: "Bratislava", major: ["Košice", "Prešov"] },
  si: { capital: "Ljubljana", major: ["Maribor", "Celje"] },
  sb: { capital: "Honiara", major: [] },
  so: { capital: "Mogadishu", major: ["Hargeisa", "Kismayo"] },
  za: { capital: "Pretoria", major: ["Johannesburg", "Cape Town", "Durban", "Port Elizabeth", "Bloemfontein"] },
  kr: { capital: "Seoul", major: ["Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon"] },
  ss: { capital: "Juba", major: ["Malakal"] },
  es: { capital: "Madrid", major: ["Barcelona", "Valencia", "Seville", "Bilbao", "Málaga", "Zaragoza", "Palma"] },
  lk: { capital: "Sri Jayawardenepura Kotte", major: ["Colombo", "Kandy", "Galle"] },
  sd: { capital: "Khartoum", major: ["Omdurman", "Port Sudan"] },
  sr: { capital: "Paramaribo", major: [] },
  se: { capital: "Stockholm", major: ["Gothenburg", "Malmö", "Uppsala", "Linköping"] },
  ch: { capital: "Bern", major: ["Zürich", "Geneva", "Basel", "Lausanne", "Lucerne"] },
  sy: { capital: "Damascus", major: ["Aleppo", "Homs", "Latakia"] },
  tw: { capital: "Taipei", major: ["Kaohsiung", "Taichung", "Tainan", "Taoyuan"] },
  tj: { capital: "Dushanbe", major: ["Khujand"] },
  tz: { capital: "Dodoma", major: ["Dar es Salaam", "Mwanza", "Arusha", "Zanzibar City"] },
  th: { capital: "Bangkok", major: ["Chiang Mai", "Phuket", "Pattaya", "Nonthaburi", "Hat Yai"] },
  tl: { capital: "Dili", major: [] },
  tg: { capital: "Lomé", major: ["Kara"] },
  to: { capital: "Nuku'alofa", major: [] },
  tt: { capital: "Port of Spain", major: ["San Fernando", "Chaguanas"] },
  tn: { capital: "Tunis", major: ["Sfax", "Sousse", "Gabès"] },
  tr: { capital: "Ankara", major: ["Istanbul", "Izmir", "Bursa", "Antalya", "Adana"] },
  tm: { capital: "Ashgabat", major: ["Turkmenabat", "Daşoguz"] },
  tv: { capital: "Funafuti", major: [] },
  ug: { capital: "Kampala", major: ["Gulu", "Mbale"] },
  ua: { capital: "Kyiv", major: ["Kharkiv", "Odesa", "Dnipro", "Lviv", "Zaporizhzhia"] },
  ae: { capital: "Abu Dhabi", major: ["Dubai", "Sharjah", "Ajman", "Ras Al Khaimah"] },
  gb: { capital: "London", major: ["Manchester", "Birmingham", "Glasgow", "Liverpool", "Edinburgh", "Leeds", "Bristol", "Sheffield", "Newcastle"] },
  us: { capital: "Washington, D.C.", major: ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Nashville"] },
  uy: { capital: "Montevideo", major: ["Salto", "Punta del Este"] },
  uz: { capital: "Tashkent", major: ["Samarkand", "Bukhara", "Namangan"] },
  vu: { capital: "Port Vila", major: ["Luganville"] },
  va: { capital: "Vatican City", major: [] },
  ve: { capital: "Caracas", major: ["Maracaibo", "Valencia", "Barquisimeto"] },
  vn: { capital: "Hanoi", major: ["Ho Chi Minh City", "Da Nang", "Haiphong", "Can Tho"] },
  ye: { capital: "Sana'a", major: ["Aden", "Taiz", "Hodeidah"] },
  zm: { capital: "Lusaka", major: ["Kitwe", "Ndola"] },
  zw: { capital: "Harare", major: ["Bulawayo", "Chitungwiza"] },
};

const cityMultiplier = {
  capital: 1.15,
  major: 1.05,
  small: 0.95,
};

const cities = [];

for (const c of countries) {
  const info = capitalData[c.code];
  if (!info) {
    cities.push({
      code: c.code,
      countrySlug: c.slug,
      countryName: c.name,
      slug: c.slug,
      name: c.name,
      type: "capital",
    });
    continue;
  }

  cities.push({
    code: c.code,
    countrySlug: c.slug,
    countryName: c.name,
    slug: `${c.slug}-capital`.replace(/\s+/g, "-").toLowerCase(),
    name: info.capital,
    type: "capital",
  });

  for (const city of info.major) {
    const citySlug = city.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
    cities.push({
      code: c.code,
      countrySlug: c.slug,
      countryName: c.name,
      slug: `${citySlug}-${c.code}`,
      name: city,
      type: "major",
    });
  }
}

fs.writeFileSync("src/data/cities.json", JSON.stringify(cities, null, 2));
console.log(`Generated ${cities.length} cities`);
